### ISSUE TITLE
No PV input wattage and AC Input

### ISSUE THREAD

**Issue by raymondrudman** [JosefKrieglstein/AxpertControl#1]
All other PV inputs are available except for the PV wattage and all AC inputs. All the AC outputs are available but not the inputs, kindly please add them, will really appreciate it as I will use this script for monitoring my inverter.

**Comment by JosefKrieglstein** [comment]
Hi, it's true, My Axpert has no value for PV Input Power. I must calculate it in emoncms:
PV_input_current_for_battery ----- Log to feed, * feed, Log to feed, Power to kWh, Power to kWh/d
* feed means *Voltage, second log to feed means store Power in Watts.

It is already explained on line 14 of axpert.py.

**Comment by raymondrudman** [comment]
Hi, could you please give me an example of how to calculate the PV input power in emoncms, I am stuck with setting the feeds.


Kind regards,
Raymond

[1471453013102_logo-square.png]
<https://instagram.com/raymondrudman/>

________________________________

**Comment by JosefKrieglstein** [comment]
Hi,

PV_input_current_for_battery; Log to feed; *feed 
Battery_voltage_from_SCC; Log to feed; Power to kWh; Power to kWh/d

Storred values: Amps; Watts; kWh; kWh/d

BR

Josef Krieglstein
Dne 25. 12. 2017 v 9:42 raymondrudman napsal(a):

**Comment by raymondrudman** [comment]
I have figured it out, in the first email you said PV_Input_Voltage and now you say Battery_voltage_from_SCC, which one do I use?


Also now that I figured it out, its giving me averages, not the exact wattage that it states on the inverter, is there a way to get the exact amount that the inverter states because its a few 100w higher than what its suppose to be.


Kind regards,
Raymond

[1471453013102_logo-square.png]
<https://instagram.com/raymondrudman/>

________________________________

**Comment by raymondrudman** [comment]
I have x4 325w panels, so that gives me 1.3kW of input from my panels but max I have seen is 1.4kW, the reading from the calculation went over 2kW


Kind regards,
Raymond

[1471453013102_logo-square.png]
<https://instagram.com/raymondrudman/>

________________________________

**Comment by raymondrudman** [comment]
Hi,

I have figured all out but I have found another problem with the script.

It seems that every time the script runs, it also changes the max utility charging amperage on the inverter back to 30Amps, I sometimes use a generator and can only have it set to 10Amps else it keeps dropping the generator d



Kind regards,
Raymond

[1471453013102_logo-square.png]
<https://instagram.com/raymondrudman/>

________________________________

**Comment by raymondrudman** [comment]
Hi,

I have figured all out but I have found another problem with the script.

It seems that every time the script runs, it also changes the max utility charging amperage on the inverter back to 30Amps, I sometimes use a generator and can only have it set to 10Amps else it keeps dropping the generator due to the voltage drop from the high amperage. How can I stop the script from changing the AC charging current on the inverter.


Kind regards,
Raymond

[1471453013102_logo-square.png]
<https://instagram.com/raymondrudman/>

________________________________
